### ISSUE TITLE
Heads not showing up even when the config files are in /mods folder

### ISSUE THREAD

**Issue by extral1f3** [gb2233/BetterInventory#1]
I have done everything exactly as i was supposed to and the heads and a couple other tabs are there but empty..

**Comment by gb2233** [comment]
Hello, can you test it with the new version too? It should be fixed

**Comment by extral1f3** [comment]
Confirmed: Working Status. I have had no issues with this.
   On Sunday, June 10, 2018, 1:35:12 PM EDT, gb2233 <notifications@github.com> wrote:  
 
 
Hello, can you test it with the new version too? It should be fixed
